# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v2
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-feature-${{ hashFiles('package-lock.json') }}
          npm-feature-
          npm-

    - name: Install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose


    - name: Save node_modules as artifact
      uses: actions/upload-artifact@v3
      with:
        name: node_modules
        path: node_modules

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Restore node_modules
      uses: actions/download-artifact@v3
      with:
        name: node_modules

    - name: Run Unit Tests
      run: npm test

  test_nestjs:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Restore node_modules
      uses: actions/download-artifact@v3
      with:
        name: node_modules

    - name: Run NestJS Tests
      run: npm run test:nestjs

  test_mocha:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Restore node_modules
      uses: actions/download-artifact@v3
      with:
        name: node_modules

    - name: Run Mocha Tests
      run: npm run test:mocha